django_project/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

encyclopedia/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("search/", views.search_entry, name="search_results")
]

entry/urls.py
from django.urls import path

from . import views

app_name = "entries"

urlpatterns = [
    path("/create/", views.index, name="create"),
    path("post/", views.submit_entry, name="post"),
    path("/wiki/<str:title>/", views.read_entry, name="read"),
    path("/random/", views.random_entry, name="random"),
    path("/update/<str:title>/", views.edit_entry, name="edit"),
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls")),
    path('entry', include("entry.urls"))
]

entry/models.py
from django.db import models

# Create your models here.

class Entry(models.Model):
    content = models.TextField()

    class Meta:
        verbose_name_plural = "Encyclopedia Entry - Markdown content"

    def __str__(self):
        return self.content

encyclopedia/views.py
from django.shortcuts import render
from django import forms

from . import util

class SearchForm(forms.Form):
    q = forms.CharField(label="Search")

#Index view
def index(request):
    return render(request, "encyclopedia/index.html", {
         "form": SearchForm(),
         "entries": util.list_entries()
    })

#Search bar view
def search_entry(request):
    if request.method == "POST":
        
        form = SearchForm(request.POST)

        # Check if form data is valid (server-side)
        if form.is_valid():

            # Isolate the entry from the 'cleaned' version of form data
            query = form.cleaned_data["q"]
            
            print(query)
            #Retrieve all entries
            entries_list = util.list_entries()

            #Go through all entries and try to see if the query is in the list.
            for entry in entries_list:
                processed_entry = entry.split()[0].lower()
                if query.lower() in processed_entry:
                    entry = util.get_entry(query)
                    if entry is not None:
                        title = entry.split("#")[0]
                    else:
                        break
                    # Redirect user to list of entries
                    return render(request, "encyclopedia/read.html", {
                        "entry": entry,
                        "title": title,
                        "form": SearchForm()
                    })
            res = entries_list
            message = f"Entry for {query} may not exist. Please try a different search query."
            return render(request, "encyclopedia/search_results.html", {
                "entries": res,
                "message": message,
                "form": SearchForm()
            })
    else:
        res = util.list_entries()
        return render(request, "encyclopedia/search_result.html", {
            "form": SearchForm(),
            "entries": res
        })

entry/views.py
import random

from django import forms
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.views.generic import TemplateView, ListView
from .models import Entry
from django.db.models import Q

from encyclopedia import util

class SearchForm(forms.Form):
    q = forms.CharField(label="Search")

class NewEntryForm(forms.Form):
    title = forms.CharField(label="title", required="true")
    content = forms.CharField(label="content", widget=forms.Textarea, required="true")

class EditEntryForm(forms.Form):
    title = forms.CharField(label="title", disabled="true")
    content = forms.CharField(widget=forms.Textarea, required="true")

class EntryView(TemplateView):
    model = Entry
    template_name = 'encyclopedia/entry.html'

# Create your views here.
    
#Edit entry route
def edit_entry(request, title):
    if request.method == "POST":
        
        form = EditEntryForm(request.POST)

        # Check if form data is valid (server-side)
        if form.is_valid():
            
            # Isolate the entry from the 'cleaned' version of form data
            title = form.data["title"]
            content = form.data["content"]

            # Add the new entry to our list of entries
            util.save_entry(title, content)

            # Redirect user to list of entries
            return HttpResponseRedirect(reverse(f"/wiki/{title}"))
    else:
        if request.session['entry'] == None:
            request.session['entry'] = title
        clean_title = title.splitlines(True)[0].split("#")[0].strip()
        entry = util.get_entry(clean_title)
        
        return render(request, "encyclopedia/edit.html", {
            "title": clean_title,
            "entry": util.get_entry(clean_title),
            "entry_form": EditEntryForm(initial={'content': entry, 'title': clean_title}),
            "form": SearchForm()
        })

# Create Entry view with form to send markdown entry to backend for validation & processing. 
def index(request):
    return render(request, "encyclopedia/create.html", {
        #"placeholder": request.session['entry' or None],
        "entry_form": NewEntryForm(),
        "form": SearchForm()
    })

# Random Entry view to send markdown entry to client for viewing. 
def random_entry(request):
    if request.method == 'GET':
        entry_list = util.list_entries()
        entry = random.choice(entry_list)
        title = entry.splitlines(True)[0]
        return render(request,"encyclopedia/entry.html", {
            "entry": util.get_entry(entry),
            "title": title,
            "form": SearchForm(),
        })
    else:
        # Redirect user to list of entries
        return HttpResponseRedirect(reverse("index"))  

# Read Entry view to send markdown entry to client for viewing. 
def read_entry(request, title):

    if request.method == "GET":
        title = title.split("\r")[0]
        request.session['entry'] = title
        entry = util.get_entry(title)
        if entry is not None:
            return render(request, "encyclopedia/read.html", {
                "entry": util.get_entry(title),
                "title":  title,
                "form": SearchForm()
            })
        message = f"Entry for {title} does not exist. Please try a different entry A."
        return render(request, "encyclopedia/error.html", {
            "message": message,
            "form": SearchForm()
        })
    else:
      # Redirect user to list of entries
        return HttpResponseRedirect(reverse("index"))  

# Create Entry form validation & processing. 
def submit_entry(request):
    
    form = NewEntryForm(request.POST)
    
    if request.method == 'POST':
        # Check if form data is valid (server-side)
        if form.is_valid():

            # Isolate the entry from the 'cleaned' version of form data
            title = form.cleaned_data["title"]
            content = form.cleaned_data["content"]

            entries_list = util.list_entries()

            for entry in entries_list:
                processed_entry = entry.split()[0].lower()
                if title.lower() in processed_entry:
                    message = f"Entry for {title} already exists. Please try a different title."
                    return render(request, "encyclopedia/error.html", {
                        "message": message,
                        "form": SearchForm()
                    })

            # Add the new entry to our list of entries
            util.save_entry(title, content)

            # Redirect user to list of entries
            return HttpResponseRedirect(reverse("index"))
    else:
        # If the form is invalid, re-render the page with existing information.
        return render(request, "encyclopedia/create.html", {
            "entry_form": form,
            "form": SearchForm()
        })

encyclopedia/templates/encyclopedia/create.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Create New Page
{% endblock %}

{% block body %}
    <h1>Create a new page</h1>

    <form action="{% url 'entries:post' %}" method="post">
        {{ entry_form }}
        {% csrf_token %}
        <button type="submit">Submit</button>
    </form>

{% endblock %}

encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}
{% load markdown_extras %}

{% block title %}
    {{ title }} entry
{% endblock %}

{% block body %}
    <h1>{{ title }} entry</h1>

    <div>
        <h2>Entry to edit: {{ title }}</h2>
         <form style="display: flex; flex-direction: column;" action="{% url 'entries:edit' title=title %}" method="post">
            {% csrf_token %}
            {{ entry_form }}
            <button style="width: fit-content;" type="submit">Submit</button>
        </form> 
    </div>

{% endblock %}

encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}
{% load markdown_extras %}

{% block title %}
    Encyclopedia: Entry {{ title }}
{% endblock %}

{% block body %}
    <header class="">
        <h1>Encyclopedia: Entry</h1>
    </header>
    <article class="flex flex-col my-20 mx-auto">
        {{ entry | markdown | safe }}
    </article>
            
    <button>
        <a style="padding: 10px; " href="{% url 'entries:edit' title=title %}">Edit {{ title | markdown | safe }}</a>
    </buton>
{% endblock %}

encyclopedia/templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %}
{% load markdown_extras %}

{% block title %}
    Encyclopedia: Search Results
{% endblock %}

{% block body %}
    <header class="">
        <h1>Encyclopedia: Entry</h1>
        <p>{{ message }}</p>
    </header>
{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% load markdown_extras %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <main style="list-style:none; margin: 0 auto; width: 200px; height:fit-content; display: flex; flex-wrap: wrap; flex-direction: row;">
        {% for entry in entries %}
            <div style=" width: 200px; border-radius: 3px; border: 2px solid aliceblue; height: fit-content; margin: 20px; padding: 10px; flex-wrap: wrap; display: flex; flex-direction:row; justify-content: center; align-items:center;">
                <a href="{% url 'entries:read' title=entry.title %}">{{ entry | markdown | safe }}</a>
            </div>
        {% endfor %}
    </main>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'search_results' %}" method="post">
                    {% csrf_token %}
                    {{ form }}
                </form>
                <div>
                    <a href="{% url 'index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'entries:create' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'entries:random' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/read.html
{% extends "encyclopedia/layout.html" %}
{% load markdown_extras %}

{% block title %}
    Encyclopedia: Entry {{ title }}
{% endblock %}

{% block body %}
    <header class="">
        <h1>Encyclopedia: Entry</h1>
    </header>
    <article class="flex flex-col my-20 mx-auto">
        {{ entry | markdown | safe }}
    </article>
            
    <button>
        <a style="padding: 10px; " href="{% url 'entries:edit' title=title %}">Edit {{ title | markdown | safe }}</a>
    </buton>
{% endblock %}

encyclopedia/templates/encyclopedia/search_results.html
{% extends "encyclopedia/layout.html" %}
{% load markdown_extras %}

{% block title %}
    Encyclopedia: Search Results
{% endblock %}

{% block body %}
    <header class="">
        <h1>Encyclopedia: Entry</h1>
        <p>{{ message }}</p>
    </header>
    <article>
        <ul style="list-style: none; width: 200px; border-radius: 3px; border: 2px solid aliceblue; height: fit-content; margin: 20px; padding: 10px; flex-wrap: wrap; display: flex; flex-direction: column; justify-content: center; align-items:center;">
            {% for entry in entries %}
                <li>
                    <a href="{% url 'entries:read' title=entry.title %}">{{ entry | markdown | safe }}</a>
                </li>
            {% endfor %}
        </ul>
    </article>
{% endblock %}